ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH

FROM --platform=${BUILDPLATFORM:-linux/amd64} \
       docker.io/golang:1.19 as BUILD

WORKDIR /build
COPY . .

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} \
      go build .

###
FROM --platform=${BUILDPLATFORM:-linux/amd64} \
       docker.io/alpine
RUN apk add --no-cache git bash tini

WORKDIR /app
COPY --from=BUILD /build/laminar .
ENTRYPOINT [ "/usr/bin/tini", "--", "/app/laminar" ]
