name: Go tests

on:
  push:
  pull_request:
    # branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: "dep: gotest"
      run: go install github.com/rakyll/gotest@latest

    - name: go mod download
      run: go mod download

    - name: Test
      run: gotest -v ./...
